source-file ~/.config/tmux/tmux.base.conf

# Sets true colors, makes tmux show the same color for nvim than in normal terminal
# Make sure the same TERM env var is set in your terminal
set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'

# Prefix as Ctrl - Space
set -g prefix ^Space

# Enumerate from 1 
set -g renumber-windows on       # renumber all windows when any window is closed
set -g base-index 1
set -g pane-base-index 1

# Don't exit from tmux when closing a session
set -g detach-on-destroy off

# Zero-out escape time delay
set -g escape-time 0

# Increase history size (from 2,000)
set -g history-limit 5000

# Use system clipboard
set -g set-clipboard on

# Status bar position
set -g status-position top

# Default terminal
set -g default-terminal "${TERM}"

# Vi Keys 
setw -g mode-keys vi

# Pane coloring
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

# Activate mouse support
set -g mouse on

# Plugins and their options 
# Plugin Manager
set -g @plugin 'tmux-plugins/tpm'

# Tmux sensible defaults
set -g @plugin 'tmux-plugins/tmux-sensible'

# Allows tmux clipboard to sync with the system one
set -g @plugin 'tmux-plugins/tmux-yank'

# Save tmux state with prefix - ctrl - S, restore it with prefix - ctrl - R
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'

# Automatically restore tmux resurrect state on startup 
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore on

# Highlight pane contents and quickly copy-paste them
set -g @plugin 'fcsonline/tmux-thumbs'

# Highlights tmux icon when the prefix is pressed
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

# Open up a utility menu with fzf using prefix - ctrl - f
set -g @plugin 'sainnhe/tmux-fzf'

# Open urls from terminal 
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '2000'

# New session handler to search, switch and rename sessions
set -g @plugin 'omerxx/tmux-sessionx'
set -g @sessionx-bind 'o'
set -g @sessionx-x-path '$DOTFILES_LOCATION'
set -g @sessionx-custom-paths '$PROJECTS_LOCATION'
set -g @sessionx-bind-new-window 'ctrl-y'
set -g @sessionx-auto-accept 'off'
set -g @sessionx-window-height '85%'
set -g @sessionx-window-width '75%'
set -g @sessionx-zoxide-mode 'on'
set -g @sessionx-preview-enabled 'true'
set -g @sessionx-prompt '-> '

# Open a floating pane with prefix-p
set -g @plugin 'omerxx/tmux-floax'
set -g @floax-width '80%'
set -g @floax-height '80%'
set -g @floax-border-color 'magenta'
set -g @floax-text-color 'blue'
set -g @floax-bind 'p'
set -g @floax-change-path 'true'

# Catppuccin theming 
set -g @plugin 'omerxx/catppuccin-tmux'
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_status_modules_right "directory date_time"
set -g @catppuccin_status_modules_left "session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_session_icon ""
set -g @catppuccin_directory_text "#{b:pane_current_path}"
set -g @catppuccin_directory_icon ""
set -g @catppuccin_date_time_text "%H:%M"
set -g @catppuccin_date_time_icon "󰃰"

# Keybindings 
# Install plugins with prefix - ctrl - I, update them using prefix - ctrl - U
run '~/.config/tmux/plugins/tpm/tpm'
