# See https://wiki.hyprland.org/Configuring/Keywords/ for more
# Setting variables
$mainMod = SUPER
$files = thunar
$browser = brave --password-store=basic
$term = ghostty
$hyprDir = $HOME/.config/hypr
$scriptsDir = $HOME/.config/hypr/scripts

# Scripts
$Mako = $scriptsDir/Mako.sh
$screenshot = $scriptsDir/ScreenShot.sh
$volume = $scriptsDir/Volume.sh
$waybar = $scriptsDir/Waybar.sh
$Wofi = $scriptsDir/Wofi.sh
$WofiBig = $scriptsDir/WofiBig.sh
$WofiBeats = $scriptsDir/WofiBeats.sh 
$Clipboard = $scriptsDir/ClipManager.sh

# see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod SHIFT, R, exec, hyprctl reload
bind = $mainMod SHIFT, D, exec, $WofiBig
bind = $mainMod, D, exec, $Wofi
bind = $mainMod, Q, killactive,
bind = $mainMod SHIFT, Q, killactive, 
bind = $mainMod SHIFT, Space, togglefloating, 
bind = $mainMod, F, fullscreen
bind = $mainMod, Return, exec, $term
bind = $mainMod, T, exec, $files
bind = $mainMod SHIFT CTRL, L, exec, hyprlock
bind = $mainMod CTRL, S, exec, $WofiBeats
bind = $mainMod, W, exec, $browser
bind = $mainMod, P, exec, wlogout
bind = $mainMod ALT, V, exec, $Clipboard

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
bind = $mainMod, period, workspace, e+1
bind = $mainMod, comma, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = $mainMod, G, togglegroup
bind = $mainMod, tab, workspace, m+1
bind = $mainMod SHIFT, tab, workspace, m-1
bind = ALT, tab, cyclenext,          # change focus to another window
bind = ALT SHIFT, tab, bringactivetotop,   # bring it to the top


# Screenshot keybindings NOTE:
#bind = , Print, exec, $screenshot --now
bind = $mainMod, Print, exec, $screenshot --now
bind = $mainMod CTRL SHIFT, Print, exec, $screenshot --in5
bind = $mainMod ALT, Print, exec, $screenshot --in10
#bind = CTRL, Print, exec, $screenshot --win
#bind = SHIFT, Print, exec, $screenshot --area
bind = $mainMod SHIFT, Print, exec, $screenshot --area

# screenshot with swappy
bind = $mainMod SHIFT, S, exec, grim -g "$(slurp)" - | swappy -f -

# Screenshot keybindings for Asus G15 (no PrinSrc button)
bind = $mainMod, F6, exec, $screenshot --now
bind = $mainMod SHIFT, F6, exec, $screenshot --area
bind = $mainMod CTRL SHIFT, F6, exec, $screenshot --in5
bind = $mainMod ALT, F6, exec, $screenshot --in10

