[tools]
python = "3.12"
node = "16"
awscli = "2.13.3"
dasel = "2.3.6"
java = "17"
jq = "latest"
yarn = "1.22.19"
act = "latest"
"npm:lerna" = "3.20"
"go:gotest.tools/gotestsum" = "latest"
"go:github.com/spf13/cobra-cli" = "latest"
argocd = "2.7.1"
yq = "4.41"
"go:github.com/moveaxlab/deploy1" = "latest"
docker-compose-v1 = "latest"
loki-logcli = "latest"
"go:github.com/ankitpokhrel/jira-cli/cmd/jira" = "latest"
lua = "latest"
"go:github.com/jesseduffield/lazygit" = "latest"
"go:github.com/lcampit/ThoughtSync" = "v1.4.1"
go = "1.22"
"go:github.com/jesseduffield/lazydocker" = "latest"
protoc = "3.17.3"

[settings]
experimental = true
trusted_config_paths = ["/home/leonardo.campitelli/Projects/"]
