"$schema" = 'https://starship.rs/config-schema.json'

[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](green)" # The "symbol" segment is being set to "➜"
error_symbol = "[➜](red)"

[directory]
read_only = "󰌾"
truncate_to_repo = false
format = '[\[$path\]]($style)[$read_only]($read_only_style) '
style = "cyan"
truncation_length = 2

[git_branch]
style = "purple"
format = '[\[$symbol$branch(:$remote_branch)\]]($style) '

[git_state]
style = "yellow"

[git_commit]
style = "green"

[git_status]
untracked = '[ $count](yellow) '
staged = '[ $count](green) '
stashed = "[ ](cyan) "
deleted = '[ $count](red) '
modified = '[ $count](blue) '
behind = '[ ](purple) '
ahead = '[ ](purple) '
format = '([$all_status$ahead_behind]($style))'

[git_metrics]
disabled = false
added_style = "green"
deleted_style = "red"

[aws]
symbol = " "
format = '[\[$symbol($profile )(\($region\))\]]($style) '
style = "yellow"

[golang]
symbol = " "
format = "[$symbol($version )]($style)"
style = "cyan dimmed"

[java]
symbol = " "
format = "[$symbol($version )]($style)"
style = "red dimmed"

[nodejs]
symbol = " "
format = "[$symbol($version )]($style)"
style = "green dimmed"

[python]
symbol = " "
format = "[$symbol($version )]($style)"
style = "yellow dimmed"

[package]
disabled = true
symbol = "󰏗 "

[cmd_duration]
style = "yellow"

[[battery.display]]
threshold = 50

[lua]
disabled = true
detect_folders = []
symbol = " "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "
disabled = true

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = "⌘ "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[pijul_channel]
symbol = "🪺 "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[spack]
symbol = "🅢 "
