[tools]
python = "latest"
go = "1.25"
rust = "latest"
node = "latest"
cargo-binstall = "latest"
jq = "latest"
yq = "4.47"
fzf = "latest"
helm = "latest"
oc = "latest"
bob = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
lazydocker = "latest"
lazygit = "latest"
starship = "latest"
zoxide = "latest"
curlie = "latest"
usage = "latest"
gh = "latest"
yazi = "latest"
opencode = "latest"

"github:control-theory/gonzo" = "latest"
"github:jonas-grgt/ktea" = "latest"
"github:harveyrandall/bsky-cli" = "latest"
"github:kopecmaciej/vi-mongo" = "latest"
"github:antoniorodr/lexy" = "latest"
"github:tstack/lnav" = "latest"
"github:quantumsheep/sshs" = "latest"
"github:eduardofuncao/squix" = "latest"
"github:christo-auer/eilmeldung" = "latest"
"github:nickjer/fltn" = "latest"
"github:tanciaku/tmmpr" = "latest"
"github:max-sixty/worktrunk" = "latest"
"github:thomasschafer/scooter" = "latest"
"github:F1bonacc1/process-compose" = "latest"
"github:vektra/mockery" = "latest"
"github:jorgerojas26/lazysql" = "latest"
"github:rgwood/systemctl-tui" = "latest"
"github:unkn0wn-root/resterm" = "latest"

"go:github.com/lcampit/ThoughtSync" = "v1.5.1"
"cargo:fzf-make" = "latest"

[settings]
experimental = true
trusted_config_paths = ["/home/leonardo.campitelli/projects/"]

[settings.cargo]
binstall = true
