[tools]
python = "latest"
jq = "latest"
yq = "4.47"
go = "1.25"
rust = "latest"
"go:github.com/jesseduffield/lazygit" = "latest"
"go:github.com/lcampit/ThoughtSync" = "v1.5.1"
"go:github.com/jesseduffield/lazydocker" = "latest"
cargo-binstall = "latest"
"cargo:starship" = "latest"
"cargo:eza" = "latest"
"cargo:bat" = "latest"
"cargo:bob-nvim" = "latest"
"cargo:zoxide" = "latest"
"cargo:ripgrep" = "latest"
"cargo:git-delta" = "latest"
"cargo:fd-find" = "latest"
fzf = "latest"
helm = "latest"
oc = "latest"
"go:github.com/melkeydev/go-blueprint" = "latest"
"go:github.com/rs/curlie" = "latest"
"pipx:posting" = "latest"
"go:github.com/control-theory/gonzo/cmd/gonzo" = "latest"
"cargo:fzf-make" = "latest"
gh = "latest"
"cargo:tmmpr" = "latest"
"aqua:yazi" = "latest"
"cargo:fltn" = "latest"
"github:anomalyco/opencode" = "latest"
"go:github.com/unkn0wn-root/resterm/cmd/resterm" = "latest"
"github:jonas-grgt/ktea" = "latest"
"github:harveyrandall/bsky-cli" = "latest"
"go:github.com/f1bonacc1/process-compose" = "latest"
"go:github.com/vektra/mockery/v3" = "v3.7.0"
"github:kopecmaciej/vi-mongo" = "latest"
"go:github.com/jorgerojas26/lazysql" = "latest"
"github:antoniorodr/lexy" = "latest"
"github:vifm/vifm" = "latest"
"github:jonas/tig" = "latest"

[settings]
experimental = true
trusted_config_paths = ["/home/leonardo.campitelli/projects/"]

[settings.cargo]
binstall = true
