#!/bin/sh
alias vim='nvim'
alias clipboard='xclip -sel clip'
alias cdd="cd $DOTFILES_LOCATION"
alias cdp="cd $PROJECTS_LOCATION"
alias cat=bat
alias ls="exa"
alias terminaltheme='bash -c  "$(wget -qO- https://git.io/vQgMr)"'
alias grep=rg
alias zshrc="nvim $HOME/.zshrc"
alias t='python3 ~/t/t.py --task-dir ~/.tasks --delete-if-empty --list tasks'
alias cd='z'
alias c='z'
alias less='delta'
