#!/bin/sh
alias vim='nvim'
alias clipboard='xclip -sel clip'
alias cdd="cd $DOTFILES_LOCATION"
alias cdp="cd $PROJECTS_LOCATION"
alias cat=bat
alias ls="eza"
alias terminaltheme='bash -c  "$(wget -qO- https://git.io/vQgMr)"'
alias grep=rg
alias zshrc="nvim $HOME/.zshrc"
alias t='python3 ~/t/t.py --task-dir ~/.tasks --delete-if-empty --list tasks'
alias cd='z'
alias c='z'
alias less='delta'
alias dps='docker ps --format "{{ .Names }}\t{{ .Ports }}\t{{ .Status }}"'
alias tkill="for s in \$(tmux list-sessions | awk '{print \$1}' | rg ':' -r '' | fzf); do tmux kill-session -t \$s; done;"
alias pid="ps -aux | grep -v grep | grep -v rg | grep "
alias clock="tty-clock -tcs -C 3"
alias p='nvim `fzf --preview="bat --color always {}"`'
alias technews="curl us.getnews.tech" # also hn (haxor-news) can be used to fetch tech news on terminal
alias ll='eza --long --header --group-directories-first --git --group --all'
alias lg='lazygit'
alias lzd='lazydocker'
