. "$HOME/.cargo/env"

# editor
export EDITOR=nvim
export VISUAL=nvim

# adds go to path
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$(go env GOPATH)/bin
export GOPATH=$(go env GOPATH)

# adds rust to path
export RUSTUP_HOME=$HOME/.rustup
export CARGO_HOME=$HOME/.cargo
export PATH=$PATH:$CARGO_HOME/bin
export PATH=$PATH:$HOME/.local/share/bob/nvim-bin # add bob-nvim versions to path

# adds nvim to path
# export PATH=$PATH:/usr/local/bin/nvim/bin

# Used to start ssh agent on login
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

# adds local/bin to PATH
export PATH=$PATH:$HOME/.local/bin

# sets tmux and such config dir
export XDG_CONFIG_HOME=$HOME/.config

# sets folders for projects and dotfiles
export DOTFILES_LOCATION=$HOME/Dotfiles
export PROJECTS_LOCATION=$HOME/Desktop/Projects

# adds flutter to path
export PATH=$PATH:$HOME/flutter/bin
