# history setup
HISTFILE=$HOME/.zsh_history
SAVEHIST=10000
HISTSIZE=9999
setopt share_history 
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_verify

# sources extra file if present
source "$HOME/.zsh_extra" 2> /dev/null

# sources aliases if present
source "$HOME/.alias" 2> /dev/null

# sources fzf functions if present
source "$HOME"/.fzf_alias 2> /dev/null

# load mise, ex rtx, for zsh
eval "$(~/.local/share/mise/bin/mise activate zsh)"

# load zoxide for zsh
eval "$(zoxide init zsh)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/fzf-git.sh/fzf-git.sh ] && source ~/fzf-git.sh/fzf-git.sh

# activate starship
eval "$(starship init zsh)"

[ -f ~/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && source ~/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
[ -f ~/zsh-autosuggestions/zsh-autosuggestions.zsh ] && source ~/zsh-autosuggestions/zsh-autosuggestions.zsh
